"""Export the Python corpus to ``web/data.js`` for the static frontend.

The browser app reads ``window.__DATA__``. Keeping Python as the source of
truth and generating the JS means the data is edited in one place
(``src/lawhub/data/laws.json`` via the models) and the static site, the
API, and any tests all stay in sync.

Usage::

    python scripts/export_web.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from lawhub.repository import get_corpus            # noqa: E402
from lawhub.serialize import frontend_payload       # noqa: E402


def main() -> None:
    payload = frontend_payload(get_corpus())
    out = ROOT / "web" / "data.js"
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    out.write_text(
        "/* AUTO-GENERATED by scripts/export_web.py — do not edit by hand. */\n"
        f"window.__DATA__ = {body};\n",
        encoding="utf-8",
    )
    counts = get_corpus().counts()
    print(f"wrote {out.relative_to(ROOT)}  "
          f"({counts['laws']} laws, {counts['articles']} articles, "
          f"{counts['resources']} resources)")


if __name__ == "__main__":
    main()
